### ISSUE TITLE
Cetak Kartu Peserta Ujian

### ISSUE THREAD

**Issue by elenardi** [onyet/onyetcbt#12]
Saat melakukan cetak kartu pada website administrator, data peserta tidak muncul pada lembar pdf.

**Comment by onyet** [comment]
Silahkan sertakan langkah langkah yang di ambil saat cetak kartu peserta.

**Comment by elenardi** [comment]
login via admin -> tambah peserta ujian -> tambah data bank soal -> tambah jadwal ujian -> cetak kartu ujian dengan memilih kelas yang sesuai dengan data peserta ujian.

**Comment by onyet** [comment]
> login via admin -> tambah peserta ujian -> tambah data bank soal -> tambah jadwal ujian -> cetak kartu ujian dengan memilih kelas yang sesuai dengan data peserta ujian.

baik, akan kami tes di versi terbaru ... :)

**Comment by Kangalitea83Gth** [comment]
Malam KA Aplikasinya sudah saya test ... TERIMA KASIH sangat terbantu, 
sebagai informasi PADA MENU TATAP MUKA di dasboard/tampilan siswa masih belum muncul.
undangan TATAP MUKA yang dibuat admin untuk guru sudan muncul/tampil. namun
tatam muka yang dibuat guru untuk siswa masih belum. TERIMA KASIH
tampilan di menu guru sebagai berikut
![image](https://user-images.githubusercontent.com/82562732/115112721-0f521f00-9fb1-11eb-87bb-71db4968ee81.png)
dan berikut tampilan pada siswa :
![image](https://user-images.githubusercontent.com/82562732/115112781-5b9d5f00-9fb1-11eb-91f0-d3064e41a4e0.png)
demikian kami sampaikan terima kasih untuk updatenya di tunggu

**Comment by onyet** [comment]
> login via admin -> tambah peserta ujian -> tambah data bank soal -> tambah jadwal ujian -> cetak kartu ujian dengan memilih kelas yang sesuai dengan data peserta ujian.

Untuk kendala sudah ditemukan terdapat bug pada fungsi printkartu

```javascript
printkartu('KELAS');
```
Terimakasih karena sudah memberikan laporan kendala. akan kami proses... :)

**Comment by onyet** [comment]
> Malam KA Aplikasinya sudah saya test ... TERIMA KASIH sangat terbantu,
> sebagai informasi PADA MENU TATAP MUKA di dasboard/tampilan siswa masih belum muncul.
> undangan TATAP MUKA yang dibuat admin untuk guru sudan muncul/tampil. namun
> tatam muka yang dibuat guru untuk siswa masih belum. TERIMA KASIH
> tampilan di menu guru sebagai berikut
> ![image](https://user-images.githubusercontent.com/82562732/115112721-0f521f00-9fb1-11eb-87bb-71db4968ee81.png)
> dan berikut tampilan pada siswa :
> ![image](https://user-images.githubusercontent.com/82562732/115112781-5b9d5f00-9fb1-11eb-91f0-d3064e41a4e0.png)
> demikian kami sampaikan terima kasih untuk updatenya di tunggu

Sudah kami buat issue baru ya kak, akan kami cek terlebih dahulu. :)

**Comment by onyet** [comment]
Silahkan cek commit terakhir
