### ISSUE TITLE
Gagal Load CSS

### ISSUE THREAD

**Issue by rockydepaulo** [onyet/onyetcbt#15]
Min Mau Tanya, Kenapa yaa kok CSS nya ga ke load

**Comment by onyet** [comment]
silahkan kirim SS ya kak. kita ga tau yang anda lakukan saat instalasi. biasanya kasus ini karena website http tapi di config.default.php anda masuk setting dengan http. sekitan

**Comment by onyet** [comment]
yang tadinya http

```php
$homeurl = "http://".$_SERVER['HTTP_HOST'];
```

di ubah menjadi https

```php
$homeurl = "https://".$_SERVER['HTTP_HOST'];
```
