### ISSUE TITLE
Cetak kartu Ujian

### ISSUE THREAD

**Issue by abuarramdhani** [onyet/onyetcbt#4]
Saya coba upload OnyetCBT dihosting sebagai ujicoba disekolah kakak saya.
pada saat akan cetak kartu ujian, saat print preview tidak muncul tampilan kartu tsb mohon solusinya

# Image Delete For Your Privation

**Comment by onyet** [comment]
hi, terimakasih.
Kami akan bekerja untuk menyelesaikan issue ini.

**Comment by onyet** [comment]
Sudah saya perbaiki ya kak...
source code candycbt yang lama sudah saya perbaiki juga.
