### ISSUE TITLE
Import Soal Format .docx

### ISSUE THREAD

**Issue by abuarramdhani** [onyet/onyetcbt#5]
Satu hal lagi, saat akan import soal format .docx
saya sudah ikuti langkah-langkah yang ada namun gagal import soal
![import1](https://user-images.githubusercontent.com/52997910/98228154-cb330b00-1f8a-11eb-99c9-6c0f46dae8a6.png)
Sebelum import saya buat bank soal

![import2](https://user-images.githubusercontent.com/52997910/98228229-e56ce900-1f8a-11eb-8980-9a72cbf73648.png)
Sample soal yang akan diimport dari "Download Format" cuma saya kurangi jumlah soal nya saya sesuaikan jumlah soal di bank soal

![import3](https://user-images.githubusercontent.com/52997910/98228335-09c8c580-1f8b-11eb-94d2-13ef8de65042.png)
Saya pilih import .docx

![import4](https://user-images.githubusercontent.com/52997910/98228367-13eac400-1f8b-11eb-9215-aec29f89dff0.png)
Hasilnya seperti ini

Mohon dibantu

**Comment by abuarramdhani** [comment]
Disini Browser yang saya gunakan adalah Google Chrome, source code saya hosting, bukan di localhost,  saya harap bisa import soal berbasis .docx. Terima Kasih

**Comment by onyet** [comment]
Hi, terimakasih sudah menggunakan aplikasi kami. pastikan format benar.
dan bila masih mengalami kendala, harap gunakan import excel untuk sementara. :)
Terimakasih

**Comment by abuarramdhani** [comment]
format excel berhasil diimport namun gambar tidak muncul

**Comment by onyet** [comment]
> format excel berhasil diimport namun gambar tidak muncul

untuk gambar baiknya gunakan url atau gambar yang sudah di upload di situs anda. 😸

**Comment by onyet** [comment]
Masalah pada koneksi ke database.
