### ISSUE TITLE
error saat login peserta

### ISSUE THREAD

**Issue by edjo22** [onyet/onyetcbt#6]
bantu dong kak, saat sudah sy hosting, login sebagai admin aman2 saja, tp login sebagai peserta tampilannya seperti reload terus-terusan. Waktu masih localhost semua lancar2 saja
![error](https://user-images.githubusercontent.com/72022545/99800860-fe22f480-2b6f-11eb-877b-00080cc6704a.jpg)

**Comment by onyet** [comment]
Jangan lupa file .htaccess nya kak. Dan setingan di config nya kak. 😊

**Comment by edjo22** [comment]
Isi file htaccessnya apa saja ya? 😂

Pada tanggal Jum, 20 Nov 2020 23:40, Dian M. & Farda F. <
notifications@github.com> menulis:

**Comment by onyet** [comment]
Bisa di lihat kak di repository... :)

**Comment by edjo22** [comment]
masih sama kak, tetap loading terus2an

**Comment by onyet** [comment]
Boleh minta link ke cbt nya kak ?? Biar kami check. Atau WA kami sesuai kontak yang tertera.

**Comment by onyet** [comment]
Pastikan anda mengubah cinfigurasi subdomain atau domain, dan htaccess pada server active
