### ISSUE TITLE
Versi database tidak sama & meet tidak muncul.

### ISSUE THREAD

**Issue by premibross** [onyet/onyetcbt#8]
Mas mohon dibantu, meet di admin muncul, tapi di siswa tidak muncul.

Trus apakah ada database terbaru, disaya keterangannya versi database tidak sesuai padahal saya pake php 7.4.15

**Comment by onyet** [comment]
silahkan cantumkan detail kendala.
1. Screenshot
2. Proses instalasi
3. Pastikan di database pada tabel setting / pengaturan ubah kolom versi database sesuai dengan yang ada di config/config.ocbt.php
Pastikan data meet terhubung ke kelas yang ingin di tuju.

**Comment by premibross** [comment]
Saya coba cari tabel setting/ pengaturan untuk ubah db versi di phpmyadmin di mana ya mas, ko saya ge nemu.hehe

**Comment by premibross** [comment]
Keterangannya:
Kedalahan versi database
Mohon maaf versi database anda tidak sesuai dengan database versi ini mohon gunakan versi terbaru.

Sebagai info, saya menggunakan database yg ocbt.sql

**Comment by premibross** [comment]
Yang meet udah bisa, tinggal menghilangkan keterangan versi db salah aja

**Comment by onyet** [comment]
Untuk Versi database silahkan buka phpmyadmin atau database mysql amanger lainnya. buka pilih SQL atau SQL Command.
jalankan script berikut :

```sql
INSERT INTO `setting` (`id_setting`, `aplikasi`, `kode_sekolah`, `sekolah`, `jenjang`, `kepsek`, `nip`, `alamat`, `kecamatan`, `kota`, `telp`, `fax`, `web`, `email`, `logo`, `header`, `header_kartu`, `nama_ujian`, `versi`, `ip_server`, `waktu`, `server`, `id_server`, `url_host`, `token_api`, `sekolah_id`, `npsn`, `db_versi`) VALUES
(1,	'OCBT',	'20302130',	'SMK SPM NASIONAL PURWOKERTO',	'SMK',	'DMW',	'-',	'Jalan Kyai Haji Wachid Hasyim No. 93, Karangklesem, Purwokerto Selatan',	'Purwokerto Selatan',	'Purwokerto',	'0281 631 952',	'-',	'www.spmnasionalpwt.sch.id',	'spmnasionalpwt@gmail.com',	'dist/img/logo87.png',	'',	'KARTU PESERTA',	'ULANGAN HARIAN',	'3.0',	'139.180.158.157',	'Asia/Jakarta',	'pusat',	'SR01',	'http://localhost',	'fqyhJuxulHCA90',	'8cce47df-aae7-4274-83cb-5af3093eab56',	'69787351',	'8.0.21');
```

**Comment by premibross** [comment]
Siap.terimakasih mas
